/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsGoalRouteImport } from './routes/settings.goal'
import { Route as LabAiFoodsRouteImport } from './routes/lab.ai-foods'
import { Route as AuthSignup2RouteImport } from './routes/auth.signup 2'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthReset2RouteImport } from './routes/auth.reset 2'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthLogin2RouteImport } from './routes/auth.login 2'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgot2RouteImport } from './routes/auth.forgot 2'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGoalRoute = SettingsGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => SettingsRoute,
} as any)
const LabAiFoodsRoute = LabAiFoodsRouteImport.update({
  id: '/lab/ai-foods',
  path: '/lab/ai-foods',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignup2Route = AuthSignup2RouteImport.update({
  id: '/auth/signup 2',
  path: '/auth/signup 2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReset2Route = AuthReset2RouteImport.update({
  id: '/auth/reset 2',
  path: '/auth/reset 2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogin2Route = AuthLogin2RouteImport.update({
  id: '/auth/login 2',
  path: '/auth/login 2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgot2Route = AuthForgot2RouteImport.update({
  id: '/auth/forgot 2',
  path: '/auth/forgot 2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/forgot 2': typeof AuthForgot2Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/login 2': typeof AuthLogin2Route
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset 2': typeof AuthReset2Route
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signup 2': typeof AuthSignup2Route
  '/lab/ai-foods': typeof LabAiFoodsRoute
  '/settings/goal': typeof SettingsGoalRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/forgot 2': typeof AuthForgot2Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/login 2': typeof AuthLogin2Route
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset 2': typeof AuthReset2Route
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signup 2': typeof AuthSignup2Route
  '/lab/ai-foods': typeof LabAiFoodsRoute
  '/settings/goal': typeof SettingsGoalRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/forgot 2': typeof AuthForgot2Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/login 2': typeof AuthLogin2Route
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset 2': typeof AuthReset2Route
  '/auth/signup': typeof AuthSignupRoute
  '/auth/signup 2': typeof AuthSignup2Route
  '/lab/ai-foods': typeof LabAiFoodsRoute
  '/settings/goal': typeof SettingsGoalRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/history'
    | '/settings'
    | '/auth/forgot'
    | '/auth/forgot 2'
    | '/auth/login'
    | '/auth/login 2'
    | '/auth/reset'
    | '/auth/reset 2'
    | '/auth/signup'
    | '/auth/signup 2'
    | '/lab/ai-foods'
    | '/settings/goal'
    | '/settings/notifications'
    | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/history'
    | '/settings'
    | '/auth/forgot'
    | '/auth/forgot 2'
    | '/auth/login'
    | '/auth/login 2'
    | '/auth/reset'
    | '/auth/reset 2'
    | '/auth/signup'
    | '/auth/signup 2'
    | '/lab/ai-foods'
    | '/settings/goal'
    | '/settings/notifications'
    | '/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/history'
    | '/settings'
    | '/auth/forgot'
    | '/auth/forgot 2'
    | '/auth/login'
    | '/auth/login 2'
    | '/auth/reset'
    | '/auth/reset 2'
    | '/auth/signup'
    | '/auth/signup 2'
    | '/lab/ai-foods'
    | '/settings/goal'
    | '/settings/notifications'
    | '/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  AuthForgotRoute: typeof AuthForgotRoute
  AuthForgot2Route: typeof AuthForgot2Route
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogin2Route: typeof AuthLogin2Route
  AuthResetRoute: typeof AuthResetRoute
  AuthReset2Route: typeof AuthReset2Route
  AuthSignupRoute: typeof AuthSignupRoute
  AuthSignup2Route: typeof AuthSignup2Route
  LabAiFoodsRoute: typeof LabAiFoodsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/goal': {
      id: '/settings/goal'
      path: '/goal'
      fullPath: '/settings/goal'
      preLoaderRoute: typeof SettingsGoalRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/lab/ai-foods': {
      id: '/lab/ai-foods'
      path: '/lab/ai-foods'
      fullPath: '/lab/ai-foods'
      preLoaderRoute: typeof LabAiFoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup 2': {
      id: '/auth/signup 2'
      path: '/auth/signup 2'
      fullPath: '/auth/signup 2'
      preLoaderRoute: typeof AuthSignup2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset 2': {
      id: '/auth/reset 2'
      path: '/auth/reset 2'
      fullPath: '/auth/reset 2'
      preLoaderRoute: typeof AuthReset2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login 2': {
      id: '/auth/login 2'
      path: '/auth/login 2'
      fullPath: '/auth/login 2'
      preLoaderRoute: typeof AuthLogin2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot 2': {
      id: '/auth/forgot 2'
      path: '/auth/forgot 2'
      fullPath: '/auth/forgot 2'
      preLoaderRoute: typeof AuthForgot2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsGoalRoute: typeof SettingsGoalRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsGoalRoute: SettingsGoalRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRouteWithChildren,
  AuthForgotRoute: AuthForgotRoute,
  AuthForgot2Route: AuthForgot2Route,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogin2Route: AuthLogin2Route,
  AuthResetRoute: AuthResetRoute,
  AuthReset2Route: AuthReset2Route,
  AuthSignupRoute: AuthSignupRoute,
  AuthSignup2Route: AuthSignup2Route,
  LabAiFoodsRoute: LabAiFoodsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
